import type { Metadata } from 'next'
import { Figtree } from 'next/font/google'
import './globals.css'
import Tabs from '@/components/Tabs'

const font = Figtree({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'JJFYE',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Tabs>
          {children}
        </Tabs>
      </body>
    </html>
  )
}
