import type { Metadata } from 'next'
import './globals.css'
import Tabs from '@/components/Tabs'


export const metadata: Metadata = {
  title: 'JJFYE',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Tabs>
          {children}
        </Tabs>
      </body>
    </html>
  )
}
